// export const words = [
//   "change",
//   "design",
//   "experience",
//   "interaction",
//   "tomorrow",
//   "ultra",
//   "life",
//   "chance",
//   "opportunity",
//   "moment",
//   "immersive",
//   "change",
//   "design",
//   "experience",
//   "interaction",
//   "tomorrow",
//   "ultra",
//   "life",
//   "chance",
//   "opportunity",
//   "moment",
//   "immersive",
//   "change",
//   "design",
//   "experience",
//   "interaction",
//   "tomorrow",
//   "ultra",
//   "life",
//   "chance",
//   "opportunity",
//   "moment",
//   "immersive",
//   "change",
//   "design",
//   "experience",
//   "interaction",
//   "tomorrow",
//   "ultra",
//   "life",
//   "chance",
//   "opportunity",
//   "moment",
//   "immersive",
//   "change",
//   "design",
//   "experience",
//   "interaction",
//   "tomorrow",
//   "ultra",
//   "life",
//   "chance",
//   "opportunity",
//   "moment",
//   "immersive",
// ];

export const words = [
  "love", "joy", "peace", "prosperity", "hope", "patience", "kindness", "goodness", "faithfulness", "gentleness", "self-control",
  "love", "joy", "peace", "prosperity", "hope", "patience", "kindness", "goodness", "faithfulness", "gentleness", "self-control",
  "love", "joy", "peace", "prosperity", "hope", "patience", "kindness", "goodness", "faithfulness", "gentleness", "self-control",
  "love", "joy", "peace", "prosperity", "hope", "patience", "kindness", "goodness", "faithfulness", "gentleness", "self-control",
  "love", "joy", "peace", "prosperity", "hope", "patience", "kindness", "goodness", "faithfulness", "gentleness", "self-control",
]