import type { Metadata } from "next";
import "../styles/globals.css";
import BodyWrapper from "@/components/BodyWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// More specific type for layout props
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <BodyWrapper className="antialiased">
        {children}
      </BodyWrapper>
    </html>
  );
}